name: CICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      -name: Clone the code
      run: echo "cloning the code"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      -name: Build using docker
      run: echo "Building using docker"
      
  test:
    needs: [build]
    runs-on:  ubuntu-latest
    steps:
      -name:  running tests
      run: echo "running tests"

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      -name: deploying
      run: echo "deploying"

    
    
